import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store, seed } from '../src/core.mjs';
import { Payment } from '../src/service.mjs';
import { createServer } from '../src/server.mjs';
test('HTTP session, Origin, gateway identity, idempotency and isolation',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pog-http-'));
 const store=new Store(dir,seed('demo','demo-v1'));
 const secret='x'.repeat(64),server=createServer(new Payment(store),{secret});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const url=`http://127.0.0.1:${server.address().port}`;
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));store.close();fs.rmSync(dir,{recursive:true,force:true});});
 const request=(route,options={})=>fetch(url+route,options);
 const post=(body,more={})=>({method:'POST',headers:{Origin:url,'Content-Type':'application/json',...more},body:JSON.stringify(body)});
 assert.equal((await request('/api/state')).status,401);
 assert.equal((await request('/api/state',{headers:{'x-payment-user':'admin'}})).status,401);
 assert.equal((await request('/api/login',post({username:'donor',password:'wrong'}))).status,401);
 const login=await request('/api/login',post({username:'donor',password:'PoG-demo-2026'}));
 assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];
 assert.equal((await request('/api/operations/exchange',post({amount:'60'},{Cookie:cookie,Origin:'http://evil.test','Idempotency-Key':'http-request'}))).status,403);
 const options=post({amount:'60'},{Cookie:cookie,'Idempotency-Key':'http-request'});
 const first=await (await request('/api/operations/exchange',options)).json();
 const second=await (await request('/api/operations/exchange',options)).json();assert.equal(first.id,second.id);
 const view=await (await request('/api/state',{headers:{Cookie:cookie}})).json();assert.equal(view.user.hkdCents,94000);
 const other=await (await request('/api/state',{headers:{'x-payment-secret':secret,'x-payment-user':'donor2'}})).json();assert.equal(other.operations.length,0);
 assert.equal((await request('/api/operations/pause',post({projectId:'P-001',reason:'x'},{Cookie:cookie,'Idempotency-Key':'forbidden-action'}))).status,403);
 assert.equal((await request('/api/operations/exchange',post({amount:'1',extra:'x'.repeat(17000)},{Cookie:cookie,'Idempotency-Key':'large-payload'}))).status,413);
 assert.equal((await request('/api/state',{headers:{'x-payment-secret':secret,'x-payment-user':'__proto__'}})).status,403);
 assert.equal((await request('/app.js')).status,200);
});
