"""M3.3-A's narrow saved-signature bridge, using an actual owned HTTP server.

Only the accepted fixture's project/deposit/PO baseline uses TestClient. All
sign-demo, submit-signed and subsequent business requests cross loopback HTTP.
No signature is read from SQL or generated by the test; no credentials are
printed. Synthetic PRE/MockHKD stop at ReceiptConfirmed, without release/payment.
"""
from __future__ import annotations

from collections import Counter
import os
import re
import socket
import subprocess
import sys
import time
from types import SimpleNamespace
from uuid import UUID

import httpx
import pytest
from sqlalchemy import func, select

from pog_api.models import (
    ChainEvent, ChainTransaction, Document, DocumentVersion, LedgerProjection,
    Operation, OperationStep, PolicyProjection, SigningRequest,
)
from pog_api.test_database import assert_safe_test_target


DATABASE_URL = os.environ.get("POG_TEST_DATABASE_URL") or ""
# Prove ownership before importing the destructive accepted baseline fixture.
assert_safe_test_target(DATABASE_URL)
from test_a2_receipt_confirmed import PASSWORD, _drain, _pdf  # noqa: E402
from test_a2_renewal_human import MANIFEST, REPOSITORY, renewal_env  # noqa: E402, F401


AMOUNT = 80_000_000
INVOICE = 72_000_000
FORBIDDEN_RESPONSE_FIELDS = {
    "signature", "rawsignature", "password", "token", "accesstoken",
    "authorization", "bearertoken", "privatekey", "mnemonic",
}
RAW_EOA_SIGNATURE = re.compile(r"0x[0-9a-fA-F]{130}(?![0-9a-fA-F])")

# Pass one already-bound AF_INET socket to the sole child. No free-port race,
# port scan, process-group kill, reload worker, or existing API is involved.
SERVER_PROGRAM = """
import os
import socket
import uvicorn
from pog_api.test_database import assert_safe_test_target
assert_safe_test_target(os.environ['POG_TEST_DATABASE_URL'])
listener = socket.socket(fileno=int(os.environ['POG_A3_TEST_API_FD']))
assert listener.getsockname()[0] == '127.0.0.1'
config = uvicorn.Config(
    'pog_api.app:create_app', factory=True, host='127.0.0.1',
    port=int(os.environ['POG_BIND_PORT']), access_log=False,
    log_level='critical', log_config=None, proxy_headers=False,
    lifespan='on', timeout_keep_alive=1,
)
uvicorn.Server(config).run(sockets=[listener])
"""


def _assert_public_response(response, credentials=()):
    """Raise generic failures, without including response bodies or credentials."""
    body = response.json()

    def walk(value):
        if isinstance(value, dict):
            for key, item in value.items():
                if key.lower() in FORBIDDEN_RESPONSE_FIELDS:
                    raise AssertionError("Sensitive field appeared in a public HTTP response")
                walk(item)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    walk(body)
    if RAW_EOA_SIGNATURE.search(response.text):
        raise AssertionError("Raw signature appeared in a public HTTP response")
    if any(credential and credential in response.text for credential in credentials):
        raise AssertionError("Session credential appeared in a public HTTP response")
    return body


@pytest.fixture
def signed_http_env(renewal_env, tmp_path):
    env = renewal_env
    assert_safe_test_target(DATABASE_URL)
    assert env.gateway.rpc_url == "http://127.0.0.1:18545"
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    process = None
    client = None
    try:
        listener.bind(("127.0.0.1", 0))
        listener.listen(128)
        port = listener.getsockname()[1]
        assert 1024 <= port <= 65535 and port != 18545
        child_environment = {
            name: value for name, value in os.environ.items()
            if name.lower() not in {"http_proxy", "https_proxy", "all_proxy", "no_proxy"}
        }
        child_environment.update({
            "PYTHONPATH": str(REPOSITORY / "services/api/src"),
            "POG_DATABASE_URL": DATABASE_URL,
            "POG_TEST_DATABASE_URL": DATABASE_URL,
            "POG_STORAGE_ROOT": str(tmp_path / "evidence"),
            "POG_A2_CHAIN_ENABLED": "true",
            "POG_A2_CHAIN_MANIFEST": str(MANIFEST),
            "POG_A2_DEMO_SIGNING_ENABLED": "true",
            "POG_A2_SIGNING_TTL_SECONDS": "3600",
            "POG_BIND_HOST": "127.0.0.1",
            "POG_BIND_PORT": str(port),
            "POG_A3_TEST_API_FD": str(listener.fileno()),
            "NO_PROXY": "127.0.0.1,localhost",
        })
        process = subprocess.Popen(
            [sys.executable, "-c", SERVER_PROGRAM], cwd=REPOSITORY,
            env=child_environment, pass_fds=(listener.fileno(),),
            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        listener.close()
        client = httpx.Client(
            base_url=f"http://127.0.0.1:{port}", trust_env=False,
            follow_redirects=False, timeout=15.0,
        )
        deadline = time.monotonic() + 45
        ready = False
        while time.monotonic() < deadline and process.poll() is None:
            try:
                response = client.get("/ready", timeout=1)
                if response.status_code == 200 and response.json().get("ready") is True:
                    ready = True
                    break
            except httpx.HTTPError:
                pass
            time.sleep(0.1)
        assert ready, "The owned loopback API did not become ready within its bounded startup window"
        tokens = {}
        identities = {}
        for actor in ("foundation", "recipient", "admin", "service-ai-fixture", "donor", "donor-fixture-b"):
            response = client.post("/v2/sessions", json={"username": actor, "password": PASSWORD})
            if response.status_code != 200:
                raise AssertionError("A synthetic fixture actor could not start an HTTP session")
            tokens[actor] = response.json()["token"]
            response = client.get("/v2/me", headers={"Authorization": "Bearer " + tokens[actor]})
            assert response.status_code == 200
            identities[actor] = _assert_public_response(response, (*tokens.values(), PASSWORD))

        def headers(actor, key=None):
            result = {"Authorization": "Bearer " + tokens[actor]}
            if key is not None:
                result["Idempotency-Key"] = key
            return result

        def post(path, body, actor, key, *, expected=202):
            response = client.post(path, json=body, headers=headers(actor, key))
            assert response.status_code == expected, "Unexpected HTTP mutation status"
            return _assert_public_response(response, (*tokens.values(), PASSWORD))

        def get(path, actor):
            response = client.get(path, headers=headers(actor))
            assert response.status_code == 200, "Unexpected HTTP read status"
            return _assert_public_response(response, (*tokens.values(), PASSWORD))

        def upload(actor, category, key):
            response = client.post(
                "/v2/documents", data={"procurementId": env.procurement["id"], "category": category},
                files={"file": (f"{category}.pdf", _pdf(), "application/pdf")},
                headers=headers(actor, key),
            )
            assert response.status_code == 202, "HTTP evidence upload failed"
            return _assert_public_response(response, (*tokens.values(), PASSWORD))["document"]

        # Token values remain private closure state, never fixture result data.
        yield SimpleNamespace(env=env, post=post, get=get, upload=upload, identities=identities)
    finally:
        try:
            if client is not None:
                client.close()
        finally:
            try:
                listener.close()
            finally:
                if process is not None and process.poll() is None:
                    process.terminate()
                    try:
                        process.wait(timeout=10)
                    except subprocess.TimeoutExpired:
                        process.kill()
                        process.wait(timeout=10)


def _operation_count(factory, kind):
    with factory() as session:
        return session.scalar(select(func.count(Operation.id)).where(Operation.operation_kind == kind))


def _submit_via_saved_signature(http, request, actor, key, expected_event):
    env = http.env
    request_id = request["id"]
    path = f"/v2/signing-requests/{request_id}/submit-signed"
    kind = "signing_request.submit_signed." + request["kind"]
    count_before = _operation_count(env.factory, kind)
    missing = http.post(path, {"confirm": True}, actor, key + "-unsigned", expected=409)
    assert missing["error"]["code"] == "signing_signature_missing"
    assert _operation_count(env.factory, kind) == count_before
    signed = http.post(
        f"/v2/signing-requests/{request_id}/sign-demo", {"confirm": True}, actor, key + "-sign",
    )
    assert signed["signingRequest"]["status"] == "signed"
    assert signed["signingRequest"]["digest"] == request["digest"]
    queued = http.post(path, {"confirm": True}, actor, key)
    operation = queued["operation"]
    assert (operation["status"], operation["operationKind"], operation["chainVerified"], operation["replayed"]) == (
        "queued", kind, False, False,
    )
    assert queued["signingRequest"]["status"] == "queued"
    operation_id = operation["operationId"]
    pending = http.get(f"/v2/operations/{operation_id}", actor)
    assert pending["status"] == "queued" and pending["chainVerified"] is False
    assert pending["steps"][0]["expectedEvent"] == expected_event
    with env.factory() as session:
        assert session.scalar(select(func.count(ChainTransaction.id)).where(
            ChainTransaction.operation_id == UUID(operation_id),
        )) == 0
    replay = http.post(path, {"confirm": True}, actor, key)
    assert replay["operation"]["operationId"] == operation_id
    assert replay["operation"]["replayed"] is True
    assert _operation_count(env.factory, kind) == count_before + 1
    assert env.worker.once() is True
    submitted = http.get(f"/v2/operations/{operation_id}", actor)
    assert submitted["status"] == "submitted" and submitted["chainVerified"] is False
    replay = http.post(path, {"confirm": True}, actor, key)
    assert replay["operation"]["operationId"] == operation_id and replay["operation"]["replayed"] is True
    _drain(env.worker, env.indexer, env.factory, operation_id)
    confirmed = http.get(f"/v2/operations/{operation_id}", actor)
    assert confirmed["status"] == "confirmed" and confirmed["chainVerified"] is True
    transaction = confirmed["steps"][0]["transaction"]
    assert transaction["status"] == "confirmed" and transaction["canonical"] is True
    assert transaction["receiptStatus"] == 1
    replay = http.post(path, {"confirm": True}, actor, key)
    assert replay["operation"]["operationId"] == operation_id and replay["operation"]["replayed"] is True
    assert replay["signingRequest"]["status"] == "confirmed"
    assert _operation_count(env.factory, kind) == count_before + 1
    new_key = http.post(path, {"confirm": True}, actor, key + "-different", expected=409)
    assert new_key["error"]["code"] == "signing_request_state"
    assert _operation_count(env.factory, kind) == count_before + 1
    receipt, events = env.gateway.receipt_with_events(transaction["transactionHash"], expected_event)
    assert receipt["status"] == 1 and len(events) == 1
    assert env.gateway.canonical(receipt["blockNumber"], receipt["blockHash"])
    assert events[0]["event"] == expected_event
    with env.factory() as session:
        assert session.scalar(select(func.count(ChainTransaction.id)).where(
            ChainTransaction.operation_id == UUID(operation_id),
        )) == 1
        assert session.scalar(select(func.count(ChainEvent.id)).where(
            ChainEvent.tx_hash == receipt["transactionHash"],
            ChainEvent.block_hash == receipt["blockHash"],
            ChainEvent.event_name == expected_event, ChainEvent.canonical.is_(True),
        )) == 1
    return operation_id, events[0]


def test_actual_http_three_saved_signatures_stop_at_receipt_confirmed(signed_http_env):
    http, env = signed_http_env, signed_http_env.env
    gate = env.gateway
    project_id, procurement_id = env.project["businessId"], env.procurement["businessId"]
    foundation_before = int(gate.call("MockHKD", "balanceOf", gate.roles["foundation"]))
    escrow_before = int(gate.call("MockHKD", "balanceOf", gate.contract_address("ProcurementEscrowV2")))
    assert http.identities["admin"]["username"] == "admin"
    assert http.identities["admin"]["role"] == "human_approver"
    assert len({http.identities[actor]["walletAddress"].lower()
                for actor in ("foundation", "recipient", "admin", "service-ai-fixture")}) == 4
    initial_ledger = gate.call("ProcurementEscrowV2", "getLedger", project_id)
    assert tuple(int(initial_ledger[index]) for index in (1, 2, 3, 4)) == (100_000_000, 0, 0, 0)

    ai = http.post(f"/v2/procurements/{env.procurement['id']}/signing-requests", {
        "kind": "ai_pre", "deadlineTtlSeconds": 3600,
    }, "service-ai-fixture", "a3-http-ai-request")["signingRequest"]
    assert ai["synthetic"] is True
    ai_path = f"/v2/signing-requests/{ai['id']}/submit-signed"
    for suffix, body in (("false", {"confirm": False}), ("number", {"confirm": 1}),
                         ("string", {"confirm": "true"}), ("extra", {"confirm": True, "caller": gate.roles["foundation"]})):
        http.post(ai_path, body, "service-ai-fixture", "a3-invalid-confirm-" + suffix, expected=422)
    ai_operation, ai_event = _submit_via_saved_signature(
        http, ai, "service-ai-fixture", "a3-http-ai-submit", "AIAssessmentRecorded",
    )
    assert ai_event["args"]["signer"].lower() == gate.roles["aiSigner"].lower()
    assert int(gate.call("PoGRegistryV2", "aiNonces", gate.roles["aiSigner"])) == int(ai["nonce"]) + 1
    assert int(gate.call("PoGRegistryV2", "getProcurement", procurement_id)[-1]) == 2

    human = http.post(f"/v2/procurements/{env.procurement['id']}/signing-requests", {
        "kind": "reserve", "reserveAmountAtomic": str(AMOUNT), "deadlineTtlSeconds": 3600,
    }, "admin", "a3-http-human-request")["signingRequest"]
    assert human["typedData"]["message"]["assessmentId"] == ai["typedData"]["message"]["assessmentId"]
    forbidden = http.post(f"/v2/signing-requests/{human['id']}/submit-signed", {"confirm": True},
                          "foundation", "a3-foundation-not-human", expected=403)
    assert forbidden["error"]["code"] == "role_forbidden"
    human_operation, human_event = _submit_via_saved_signature(
        http, human, "admin", "a3-http-human-submit", "HumanApprovalSubmitted",
    )
    assert human_event["args"]["signer"].lower() == gate.roles["humanApprover"].lower()
    assert int(human_event["args"]["action"]) == 0
    assert int(gate.call("ProcurementEscrowV2", "humanNonces", gate.roles["humanApprover"])) == int(human["nonce"]) + 1
    # Signature submission creates a vote, not a reserve execution or release.
    assert int(gate.call("PoGRegistryV2", "getProcurement", procurement_id)[-1]) == 3
    assert int(gate.call("ProcurementEscrowV2", "getLedger", project_id)[2]) == 0
    with env.factory() as session:
        assert session.scalar(select(func.count(OperationStep.id)).where(OperationStep.kind == "reserve.execute")) == 0
    execute = http.post(f"/v2/procurements/{env.procurement['id']}/chain/reserve", {
        "reserveAmountAtomic": str(AMOUNT),
    }, "foundation", "a3-http-explicit-reserve")
    _drain(env.worker, env.indexer, env.factory, execute["operation"]["operationId"])

    invoice = http.upload("foundation", "invoice", "a3-http-invoice-document")
    goods = http.upload("foundation", "goods_evidence", "a3-http-goods-document")
    invoice_operation = http.post(f"/v2/procurements/{env.procurement['id']}/chain/invoice-and-goods", {
        "invoiceDocumentVersionId": invoice["versionId"], "goodsDocumentVersionId": goods["versionId"],
        "invoiceAmountAtomic": str(INVOICE),
    }, "foundation", "a3-http-invoice-submit")
    _drain(env.worker, env.indexer, env.factory, invoice_operation["operation"]["operationId"])
    evidence = http.upload("recipient", "receipt_evidence", "a3-http-recipient-evidence")
    receipt_request = http.post(f"/v2/procurements/{env.procurement['id']}/signing-requests", {
        "kind": "receipt", "receiptEvidenceDocumentVersionId": evidence["versionId"], "deadlineTtlSeconds": 3600,
    }, "recipient", "a3-http-recipient-request")["signingRequest"]
    receipt_operation, receipt_event = _submit_via_saved_signature(
        http, receipt_request, "recipient", "a3-http-recipient-submit", "RecipientReceiptAccepted",
    )
    assert receipt_event["args"]["recipient"].lower() == gate.roles["recipient"].lower()
    assert receipt_event["args"]["receiptDigest"] == receipt_request["digest"]
    assert int(gate.call("PoGRegistryV2", "recipientNonces", gate.roles["recipient"])) == int(receipt_request["nonce"]) + 1
    procurement = http.get(f"/v2/procurements/{env.procurement['id']}", "foundation")
    assert procurement["chainState"]["status"] == "receipt_confirmed"
    assert procurement["chainState"]["verified"] is True
    view = gate.call("PoGRegistryV2", "getProcurement", procurement_id)
    assert int(view[-1]) == 6 and int(view[9]) == AMOUNT and int(view[11]) == INVOICE
    assert "0x" + bytes(view[13]).hex() == receipt_request["digest"]
    ledger = gate.call("ProcurementEscrowV2", "getLedger", project_id)
    assert tuple(int(ledger[index]) for index in (1, 2, 3, 4)) == (100_000_000, AMOUNT, 0, 0)
    assert int(gate.call("ProcurementEscrowV2", "freeLocked", project_id)) == 20_000_000
    assert int(gate.call("MockHKD", "balanceOf", gate.roles["foundation"])) == foundation_before
    assert int(gate.call("MockHKD", "balanceOf", gate.contract_address("ProcurementEscrowV2"))) == escrow_before
    for actor, role, amount in (("donor", "donorA", 60_000_000), ("donor-fixture-b", "donorB", 40_000_000)):
        assert int(gate.call("ProcurementEscrowV2", "donorCredit", project_id, gate.roles[role])) == amount
        donor_ledger = http.get(f"/v2/projects/{env.project['id']}/ledger", actor)
        assert (donor_ledger["depositsAtomic"], donor_ledger["reservedAtomic"], donor_ledger["releasedAtomic"],
                donor_ledger["currentCallerDonorCreditAtomic"]) == ("100000000", str(AMOUNT), "0", str(amount))

    # Read only public material/projections/pointers, never SigningRequest.signature
    # or OperationStep.detail/ChainTransaction.calldata (which embed signatures).
    with env.factory() as session:
        requests = session.execute(select(
            SigningRequest.kind, SigningRequest.status, SigningRequest.nonce_text,
            SigningRequest.submitted_operation_id, SigningRequest.context_json,
        )).all()
        assert {row.kind for row in requests} == {"ai_pre", "reserve", "receipt"}
        assert all(row.status == "confirmed" for row in requests)
        assert {str(row.submitted_operation_id) for row in requests} == {ai_operation, human_operation, receipt_operation}
        original = session.execute(select(
            DocumentVersion.uploaded_by_user_id, DocumentVersion.keccak256_hex, DocumentVersion.referenced,
            Document.namespace_id, Document.procurement_id, Document.category,
        ).join(Document, DocumentVersion.document_id == Document.id).where(
            DocumentVersion.id == UUID(evidence["versionId"]),
        )).one()
        assert str(original.uploaded_by_user_id) == http.identities["recipient"]["id"]
        assert original.category == "receipt_evidence" and original.referenced is True
        assert str(original.procurement_id) == env.procurement["id"]
        assert receipt_request["typedData"]["message"]["receiptEvidenceHash"] == "0x" + original.keccak256_hex
        receipt_row = next(row for row in requests if row.kind == "receipt")
        assert receipt_row.context_json["receiptEvidenceDocumentVersionId"] == evidence["versionId"]
        policy = session.execute(select(
            PolicyProjection.policy_epoch, PolicyProjection.threshold, PolicyProjection.approver_wallets,
            PolicyProjection.block_number, PolicyProjection.block_hash,
        ).where(PolicyProjection.project_id == UUID(env.project["id"]))).one()
        assert policy.policy_epoch == int(ledger[9]) == int(human["policyEpoch"])
        assert policy.threshold == int(ledger[10]) == 1
        assert policy.approver_wallets == [gate.roles["humanApprover"].lower()]
        assert gate.canonical(policy.block_number, policy.block_hash)
        projection = session.execute(select(
            LedgerProjection.deposits_atomic, LedgerProjection.reserved_atomic, LedgerProjection.released_atomic,
        ).where(LedgerProjection.project_id == UUID(env.project["id"]))).one()
        assert tuple(int(value) for value in projection) == (100_000_000, AMOUNT, 0)
        actions = Counter(session.scalars(select(OperationStep.kind)))
        assert actions == Counter({
            "project.create": 1, "donation.approve": 2, "donation.deposit": 2,
            "procurement.create": 1, "procurement.po": 1, "assessment.ai_pre": 1,
            "approval.reserve": 1, "reserve.execute": 1, "procurement.invoice": 1, "receipt.submit": 1,
        })
