"""a1 foundation schema

Revision ID: 84fcc48891be
Revises:
Create Date: 2026-10-03 11:05:19.610831
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '84fcc48891be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('genesis_hash', sa.String(length=66), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('mock', 'verified')", name='ck_deployment_mode'),
    sa.CheckConstraint("verified = false OR mode = 'verified'", name='ck_verified_mode'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'instance_id', name='uq_deployment_namespace')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.bulk_insert(
        sa.table('roles', sa.column('name', sa.String())),
        [
            {'name': 'foundation'},
            {'name': 'recipient'},
            {'name': 'donor'},
            {'name': 'human_approver'},
            {'name': 'service_ai'},
            {'name': 'service_payment'},
        ],
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chain_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['deployment_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'contract_address', 'tx_hash', 'log_index', 'block_hash', name='uq_chain_event_identity')
    )
    op.create_table('indexer_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.String(length=80), nullable=False),
    sa.Column('next_block', sa.Integer(), nullable=False),
    sa.Column('last_block_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['deployment_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'consumer_name', name='uq_indexer_cursor')
    )
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('operation_kind', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_resource_type', sa.String(length=40), nullable=True),
    sa.Column('result_resource_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_status', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("idempotency_key ~ '^[ -~]+$'", name='ck_idem_printable_ascii'),
    sa.CheckConstraint('error_status IS NULL OR error_status BETWEEN 400 AND 599', name='ck_operation_error_status'),
    sa.CheckConstraint("status IN ('awaiting_authorization','queued','submitted','confirmed','failed','requires_attention','invalidated_instance')", name='ck_operation_status'),
    sa.CheckConstraint('char_length(idempotency_key) BETWEEN 1 AND 128', name='ck_idem_length'),
    sa.ForeignKeyConstraint(['namespace_id'], ['deployment_instances.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace_id', 'principal_id', 'operation_kind', 'idempotency_key', name='uq_operation_idempotency')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.String(length=66), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('public_summary', sa.Text(), nullable=False),
    sa.Column('foundation_user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('human_approver_user_id', sa.UUID(), nullable=False),
    sa.Column('foundation_wallet', sa.String(length=42), nullable=False),
    sa.Column('recipient_wallet', sa.String(length=42), nullable=False),
    sa.Column('asset_symbol', sa.String(length=16), nullable=False),
    sa.Column('fairness_rule', sa.Text(), nullable=False),
    sa.Column('chain_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_id ~ '^0x[0-9a-f]{64}$'", name='ck_project_business_id'),
    sa.CheckConstraint("chain_status = 'off_chain_draft'", name='ck_a1_project_chain_status'),
    sa.ForeignKeyConstraint(['foundation_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['human_approver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['deployment_instances.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'namespace_id', name='uq_project_id_namespace'),
    sa.UniqueConstraint('namespace_id', 'business_id', name='uq_project_namespace_business')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_session_expiry'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('wallet_authorizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("wallet_address ~ '^0x[0-9a-fA-F]{40}$'", name='ck_wallet_address'),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_name', name='uq_wallet_auth_user_role'),
    sa.UniqueConstraint('wallet_address', 'role_name', name='uq_wallet_auth_wallet_role')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=True),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('calldata_hash', sa.String(length=66), nullable=True),
    sa.Column('receipt_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('canonical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'step_index', name='uq_operation_step_index')
    )
    op.create_table('procurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.String(length=66), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('foundation_user_id', sa.UUID(), nullable=False),
    sa.Column('vendor_wallet', sa.String(length=42), nullable=False),
    sa.Column('budget_cap_atomic', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('chain_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("business_id ~ '^0x[0-9a-f]{64}$'", name='ck_proc_business_id'),
    sa.CheckConstraint("chain_status = 'off_chain_draft'", name='ck_a1_proc_chain_status'),
    sa.CheckConstraint('budget_cap_atomic >= 0 AND budget_cap_atomic <= 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='ck_proc_budget_uint256'),
    sa.ForeignKeyConstraint(['foundation_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['namespace_id'], ['deployment_instances.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'namespace_id'], ['projects.id', 'projects.namespace_id'], name='fk_proc_project_namespace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'namespace_id', name='uq_proc_id_namespace'),
    sa.UniqueConstraint('namespace_id', 'business_id', name='uq_proc_namespace_business')
    )
    op.create_table('approval_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procurement_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('signer_wallet', sa.String(length=42), nullable=True),
    sa.Column('nonce_text', sa.String(length=78), nullable=True),
    sa.Column('policy_epoch', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('procurement_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['deployment_instances.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procurement_id', 'namespace_id'], ['procurements.id', 'procurements.namespace_id'], name='fk_document_procurement_namespace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_operation_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procurement_id', sa.UUID(), nullable=False),
    sa.Column('provider_operation_id', sa.String(length=128), nullable=False),
    sa.Column('amount_atomic', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_atomic >= 0 AND amount_atomic <= 115792089237316195423570985008687907853269984665640564039457584007913129639935', name='ck_payment_amount_uint256'),
    sa.CheckConstraint("mode IN ('unavailable','mock')", name='ck_payment_mode'),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_operation_id', name='uq_payment_provider_operation')
    )
    op.create_table('risk_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procurement_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=True),
    sa.Column('report_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('keccak256_hex', sa.String(length=64), nullable=False),
    sa.Column('abi_combination_keccak_hex', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('referenced', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type IN ('application/pdf','image/jpeg','image/png')", name='ck_document_content_type'),
    sa.CheckConstraint('char_length(keccak256_hex) = 64', name='ck_document_keccak'),
    sa.CheckConstraint('char_length(sha256_hex) = 64', name='ck_document_sha256'),
    sa.CheckConstraint('size_bytes BETWEEN 1 AND 10485760', name='ck_document_size'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_document_version'),
    sa.UniqueConstraint('storage_key', name='uq_document_storage_key')
    )
    op.create_table('receipt_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procurement_id', sa.UUID(), nullable=False),
    sa.Column('evidence_document_version_id', sa.UUID(), nullable=True),
    sa.Column('signer_wallet', sa.String(length=42), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_version_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_proofs')
    op.drop_table('document_versions')
    op.drop_table('risk_reports')
    op.drop_table('payment_operation_links')
    op.drop_table('documents')
    op.drop_table('approval_records')
    op.drop_table('procurements')
    op.drop_table('operation_steps')
    op.drop_table('chain_transactions')
    op.drop_table('audit_logs')
    op.drop_table('wallet_authorizations')
    op.drop_table('sessions')
    op.drop_table('projects')
    op.drop_table('operations')
    op.drop_table('indexer_cursors')
    op.drop_table('chain_events')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('deployment_instances')
    # ### end Alembic commands ###
